<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Basket'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart custom23 w-full">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="w-full">
          <div class="w-full">
              <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Quantity') ?></span></label>
              <div class="control">
                  <span class="minus py-4 px-5">
                    <button class="py-5 px-12 rounded-4" type="button" title="<?= __('Reduce the quantity'); ?>">
                       -
                    </button>
                </span>
                  <input type="number"
                         name="qty"
                         id="qty"
                         maxlength="12"
                         value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                         title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                         data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                         />
                  <span class="plus py-4 px-4">
                    <button class="py-5 px-12 rounded-4" type="button" title="<?= __('Increase the quantity'); ?>" />
               +
                </button>
                </span>
                  <script type="text/javascript">
                      // This is the javascript codes help us to increase and decrease qty
                      require(['jquery'], function($) {
                          $('.box-tocart .minus').on('click', function() {
                              var qty = parseInt($('#qty').val());
                              qty = qty - 1;
                              $('#qty').val(qty).trigger('change');
                          });
                          $('.box-tocart .plus').on('click', function() {
                              var qty = parseInt($('#qty').val());
                              qty = qty + 1;
                              $('#qty').val(qty).trigger('change');
                          });
                          $('#qty').on('change', function() {
                              var qty = parseInt($(this).val());
                              if (qty > 100) {
                                  $(this).val('100');
                              } else if (qty < 1) {
                                  $(this).val('1');
                              }
                          });
                      });
                  </script>
              </div>
          </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="bg-black text-white w-full min-w-[280px] flex align-center py-4 px-8 text-2xl font-semibold rounded-xl hover:bg-[#EC4899] hover:text-black transition"
                    id="product-addtocart-button">
                <span class="w-full flex items-center justify-center space-evenly">  
                    <svg xmlns="http://www.w3.org/2000/svg"
                    class="xl:w-10 xl:h-10 w-10 h-10"
                    fill="none"
                    stroke="#fff"
                    viewBox="0 0 24 24">

                    <path
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M5 8h14l-1 12H6L5 8zm4-3a3 3 0 016 0v3H9V5z"/>

                 </svg> <?= /* @escapeNotVerified */ $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
        <div class="mt-3 text-sm text-red-600 font-medium">
            🔥 Only a few left in stock
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
