<div class="bb-home-hero-wrapper">

<div class="swiper bb-home-carousel-slider-show">

        <div class="swiper-wrapper">

        <div class="swiper-slide">
            <section class="bb-home-hero" style="background-repeat: no-repeat;">

                <div class="bb-home-hero__content">

                    <div class="bb-home-hero__left">

                        <span class="bb-home-hero__eyebrow text-[#C9A227] font-semibold">
                            DESIGNER FRAGRANCES
                        </span>

                        <h1 class="text-[68px] w-[693] h-[147]">
                            Luxury Fragrances
                            For Men & Women
                        </h1>

                        <p class="max-w-[520px] mt-[24px] text-[24px] font-[400px] leading-1">
                            Discover genuine designer perfumes
                            and aftershaves from leading brands
                            including Hugo Boss, Prada and more.
                        </p>

                        <div class="bb-home-hero__buttons">

                            <a href="/shops/fragrances/mens.html"
                            class="btn-primary bg-[#111827] rounded-[12px] text-white text-[12px] w-[220px] h-[40px] z-[2]  text-center py-4 ">
                                Shop Men's Fragrances
                            </a>

                            <a href="/shops/fragrances/womens.html"
                            class="btn-secondary z-[2] text-[12px] text-center py-4 border-black border-solid border-[1px] w-[220px] h-[40px] rounded-[12px] hover:bg-[#111827]">
                                Shop Women's Fragrances
                            </a>

                        </div>

                    </div>

                    <div class="bb-home-hero__right flex">

                        <img
                            src="<?= $escaper->escapeUrl(
                                $block->getViewFileUrl('images/home/boss-scent.png')
                            ) ?>"
                            alt="Boss The Scent fragrance"
                            class="bottle bottle-1"
                        >

                        <img
                            src="<?= $escaper->escapeUrl(
                                $block->getViewFileUrl('images/home/boss-bottled.png')
                            ) ?>"
                            alt="Hugo Boss Bottled fragrance"
                            class="bottle bottle-2"
                        >

                    </div>

                </div>

            </section>
        </div>

        <div class="swiper-slide">  
             <section class="bb-home-hero-slide-2" style="background-repeat: no-repeat;">

                <div class="bb-home-hero__content">

                    <div class="bb-home-hero__left">

                        <span class="bb-home-hero__eyebrow text-[#000000] font-semibold">
                            THE WORLDS FINEST
                        </span>

                        <h1 class="text-[68px] w-[693] h-[147]">
                            Fragrances & Aftershaves
                        </h1>

                        <p class="max-w-[520px] mt-[24px] text-[24px] font-[400px] leading-1">
                           Discover luxury perfumes & aftershaves from the world’s most iconic brands
                        </p>

                        <div class="bb-home-hero__buttons">

                            <a href="/shops/fragrances/mens.html"
                            class="btn-primary bg-[#111827] rounded-[12px] text-white text-[12px] w-[220px] h-[40px] z-[2]  text-center py-4 ">
                                SHOP FRAGRANCES
                            </a>

                        </div>

                    </div>

                    <div class="bb-home-hero__right flex">

                        <img
                            src="<?= $escaper->escapeUrl(
                                $block->getViewFileUrl('images/home/my-way.png')
                            ) ?>"
                            alt="Giorgio Armani My Way fragrance"
                            class="bottle bottle-1"
                        >

                        <!--<img
                            src="/media/home/boss-bottled.png"
                            alt="Hugo Man"
                            class="bottle bottle-2"
                        >-->

                    </div>

                </div>

            </section>
        </div>
        
    </div>

     <div class="swiper-pagination"></div>

    <div class="swiper-button-prev"></div>

    <div class="swiper-button-next"></div>

</div>

</div>