<section class="bb-makeup-products-container py3 w-[100vw]">
    <div class="bb-makeup-container">
        <div class="bb-makeup-eyes">
                <h3>Make Products for Eyes</h3>
                <p class="subtitle">
                    To all the beauty enthusiasts out here- you would love our happiness eyeshadow palette. 
                </p>

                <p>To create dramatic eye-makeup or soft natural hues, bold cat eye, gallery eye or some nude touch, you can have it all from the variety of palettes we have in our store. You can check for Cheap Eye Shadows on our website and Buy Eye Shadows Online of your choice. To complete the eye look, buy mascara from our online store and slay your look.</p>

                <a href="/shops/cosmetics/mascara.html" class="btn-primary text-white">SHOP NOW</a>
            
        </div>
        <div class="bb-makeup-image"></div>
    </div>
</section>