 <!-- BRAND GRID -->
<section class="bb-categories py-16">

    <div class="max-w-[1440px] mx-auto px-4">
 
        <div class="bb-categories__intro">

            <?= $this->getLayout()
                ->createBlock(\Magento\Cms\Block\Block::class)
                ->setBlockId('bb-home-categories-brands-intro')
                ->toHtml(); ?>

        </div>

<div class="swiper bb-home-brands-slider-show">

        <div class="swiper-wrapper">

        <div class="swiper-slide">
            <a href="/brands/hugo-boss-fragrance.html">
           <img src="<?= $block->getViewFileUrl('images/icons/hugo-boss-icon.svg') ?>" alt="hugo boss perfumes"></a>
        </div>

        <div class="swiper-slide">  
            <a href="/brands/prada-fragrance.html">
            <img src="<?= $block->getViewFileUrl('images/icons/prada-icon.svg') ?>" alt="prada perfumes"></a>
        </div>
         <div class="swiper-slide">  
             <a href="/brands/calvin-klein-fragrance.html">
            <img src="<?= $block->getViewFileUrl('images/icons/calvin-klein-icon.svg') ?>" alt="calvin klein perfumes"></a>
        </div>
         <div class="swiper-slide">  
            <a href="/brands/burberry-fragrance.html">
            <img src="<?= $block->getViewFileUrl('images/icons/burberry-icon.svg') ?>" alt="burberry perfumes and aftershaves"></a>
        </div>
         <div class="swiper-slide">  
           <a href="/brands/jean-paul-gaultier-fragrance.html">
            <img src="<?= $block->getViewFileUrl('images/icons/jean-paul-gaultier-icon.svg') ?>" alt="jean paul gaultier perfumes"></a>
        </div>
        
    </div>

     <div class="swiper-pagination"></div>

    <div class="swiper-button-prev"></div>

    <div class="swiper-button-next"></div>

</div>


</div>

</section>