<section class="py-16 bb-smell-good-container">
    <div class="bb-categories__intro">
        <?= $this->getLayout()
        ->createBlock(\Magento\Cms\Block\Block::class)
        ->setBlockId('homepage-smell-good-intro')
        ->toHtml(); ?>
    </div>

    <p>Smelling good is not at all less important than looking good. Good fragrances not only uplift our moods, but also uplift the moods of people around us. <a href="./shops/fragrances/womens.html"> Women’s Fragrances </a> have more of a feminine smell whereas, <a href="./shops/fragrances/mens.html">Men’s Fragrances</a> have more of a masculine smell. Both men and women sometimes do not prefer too much of feminine or masculine smell, they can always opt for Unisex Fragrances. Women can check our website to Buy Women's Fragrances Online. Men may look no further to buy Men's Fragrances Online. To buy good quality <a href="./shops/fragrances/unisex.html">unisex fragrances </a> you don’t drive up to a store, all you can do is, search, select and buy.</p>

    <p>Bringing our best collection of fragrances, eyeshadow palettes, facial cleansers and lipsticks, we know what it takes to present a peace, love and happiness collection to our customers. How about somebody asking you, 'Oh, what an attractive fragrance, what are you wearing?" You take the pride in telling the brand, and from where you have purchased. We give people the variety to explore various options and the reason to be loved and feel so special.</p>

</section>